kafka {
  bootstrap-servers = "localhost:9092"
  bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}
  topic             = "linkedin-profiles"
}

elasticsearch {
  nodes = "localhost"
  nodes = ${?ES_NODES}
  port  = "9200"

  indices {
    snapshot  = "people_snapshot"
    analytics = "people_monthly_analytics"
  }
}

checkpoints {
  snapshot  = "/tmp/checkpoint/people_snapshot"
  analytics = "/tmp/checkpoint/analytics"
}
